services:
  deck_of_cards:
    build: .
    env_file: variables.env
    user: ${PUID:-1000}:${PGID:-1000}
    container_name: DoC
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/home/dev/.Xauthority:rw
      - /dev:/dev
    group_add:
      - video
      - tty
    privileged: true
    devices:
      - /dev/dri
    network_mode: host
    command: bash
